"""Add task workflow system with custom statuses

Revision ID: fd50922d6b1f
Revises: 1c96c93b699a
Create Date: 2025-09-20 14:37:32.116715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd50922d6b1f'
down_revision: Union[str, Sequence[str], None] = '1c96c93b699a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('organization_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_configs_id'), 'organization_configs', ['id'], unique=False)
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_statuses_id'), 'task_statuses', ['id'], unique=False)
    op.create_table('task_workflow_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('from_status_id', sa.Integer(), nullable=False),
    sa.Column('to_status_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_status_id'], ['task_statuses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_status_id'], ['task_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_workflow_transitions_id'), 'task_workflow_transitions', ['id'], unique=False)
    op.create_table('task_status_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('from_status_id', sa.Integer(), nullable=True),
    sa.Column('to_status_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_status_id'], ['task_statuses.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['to_status_id'], ['task_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_transitions_id'), 'task_status_transitions', ['id'], unique=False)
    op.add_column('tasks', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'task_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'])
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'organization_id')
    op.drop_column('tasks', 'status_id')
    op.drop_index(op.f('ix_task_status_transitions_id'), table_name='task_status_transitions')
    op.drop_table('task_status_transitions')
    op.drop_index(op.f('ix_task_workflow_transitions_id'), table_name='task_workflow_transitions')
    op.drop_table('task_workflow_transitions')
    op.drop_index(op.f('ix_task_statuses_id'), table_name='task_statuses')
    op.drop_table('task_statuses')
    op.drop_index(op.f('ix_organization_configs_id'), table_name='organization_configs')
    op.drop_table('organization_configs')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
